### ISSUE TITLE
Packages ...

### ISSUE THREAD

**Issue by rajm123** [JustMaier/MVC5-SPA-Angular#1]
Hello Justin,

This template is exactly what I was looking for. I have an issue though. I'm unable to find the packages and my Nuget is not able to find the packages.

I'm getting this error:

Install-Package : Unable to find package 'Angular.UI.Bootstrap'.

Sincerely,
Raj.

**Comment by JustMaier** [comment]
Raj,

Not sure why that is giving you trouble. Here is the package, you can try downloading it manually. https://www.nuget.org/packages/Angular.UI.Bootstrap/

Let me know if that works.
