### ISSUE TITLE
Registration via 3rd Party does not complete properly: 'Pop-up Blocked'

### ISSUE THREAD

**Issue by Holf** [JustMaier/MVC5-SPA-Angular#2]
Steps to reproduce on a freshly cloned copy of the Application:
- Set application up to use Google Authentication (uncomment appropriate line in Startup.Auth).
- Ensure any existing users are removed from the Database
- Start Chrome or Firefox and ensure all cookies are deleted to eradicate any previously cached Google Credentials
- Start application
- Click on 'Or Login With: Google' button
- Follow the steps requested in the resulting Google Authentication Popup:
  Authentication Popup closes, application redirects to 'RegisterExternal' page
- Enter an appropriate user name
- Click 'Sign up'

EXPECTED RESULT
- Redirect to the Authorised version of the homepage, showing 'ASP.NET' banner

ACTUAL RESULT
- Redirect to page with 'Loading...' message
- Browser shows 'Pop-up blocked' error

I am, by this point, registered, in that subsequent login attempts work and take me directly to the Authorised Homepage.

Further info:
- I've tried rebinding to a different local URI by editing the IISExpress config. Same result
- I've also tried it deployed to Azure. Same result.
- This happens in both Chrome and Firefox (latest versions at time of writing, on Windows 8 64bit).
  (- The behaviour in IE is different... sill write a dedicated issue for this.)

**Comment by JustMaier** [comment]
Thanks for the information. I'll look into this.

I'm also considering adding an option to complete the 3rd party registration process without a popup, similar to the way it is done in the VS 2013 SPA template. That would help avoid issues with pop-up blocking.

**Comment by Holf** [comment]
That would be most excellent indeed. It is also, I think, more seamless as there's no danger of a pop-up getting lost behind the main browser window, or closed etc... Also, the popup size ceases to be an issue (I've noticed that Twitter and Google, for example, have different sized auth pages).

**Comment by Holf** [comment]
Sorry... closed it again! Creature of habit (although it's getting embarrassing now).

**Comment by JustMaier** [comment]
Made popups optional and disabled them by default.

Seems to work consistently without issues following your steps to reproduce.

**Comment by Holf** [comment]
Works beautifully.
