### ISSUE TITLE
Redirect to 'RegisterExternal' page fails when using IE10

### ISSUE THREAD

**Issue by Holf** [JustMaier/MVC5-SPA-Angular#3]
Steps to reproduce:
- Set application up to use Google Authentication (uncomment appropriate line in Startup.Auth).
- Ensure any existing users are removed from the Database.
- Start IE10 and ensure all cookies are deleted to eradicate any previously cached Google Credentials.
- Start application.
- Browse to Homepage using IE10.
- Click on 'Or Login With: Google' button.
- Enter some Google Credentials into the resulting Popup and click 'Sign in'.

EXPECTED RESULT
- Authentication Popup closes.
- Application redirects to 'RegisterExternal' page.

ACTUAL RESULT
- Authentication Popup closes.
- Application remains on 'Login' page.

Further information:
- This happens both locally and when deployed to Azure.
- Having done this once, subsequent attempts to 'Ligin with: Google' cause the Authentication Popup to appear and then disappear, implying the Google Authentication part has actually worked (indeed, browsing to other Google-secured sites work fine without requiring authentication, confirming this is the case).

**Comment by JustMaier** [comment]
@Holf after quite a bit of testing and some research it looks like most browsers other than Chrome don't allow the popup window to write back to the window opener after a redirect :(

I added the ability to not use popups and it seems to work without any issues. Popups are now disabled by default.
