### ISSUE TITLE
Microsoft.AspNet.Identity.Core 2.0.x

### ISSUE THREAD

**Issue by JanickRoss** [JustMaier/MVC5-SPA-Angular#4]
Do you habe plan or ETA for updating your template at Microsoft.AspNet.Identity.Core 2.0.x

**Comment by JustMaier** [comment]
@JanickRoss  I haven't looked into Microsoft.AspNet.Identity.Core 2.0.x much yet, but it looks like it adds quite a bit of good & essential functionality. I'll look into adding support for it.

**Comment by JustMaier** [comment]
Thanks @stuisme for adding initial support for Identity.Core 2.0.x.
