### ISSUE TITLE
Templates missing

### ISSUE THREAD

**Issue by ajonesgh** [JustMaier/MVC5-SPA-Angular#7]
http://spaauth.localtest.me:65489/template/popover/popover.html 404 (Not Found)
http://spaauth.localtest.me:65489/template/alert/alert.html 404 (Not Found)

**Comment by JustMaier** [comment]
Those templates are tied to UI-Bootstrap. Can you check that anguar-ui-bootstrap.tpls is being used?

**Comment by ajonesgh** [comment]
I updated the BundleConfig.cs to include 
"~/Scripts/angular-ui/ui-bootstrap.js",
"~/Scripts/angular-ui/ui-bootstrap-tpls.js",

Looks to have fixed it :)

**Comment by JustMaier** [comment]
Great. You should only need ui-bootstrap-tpls.js, I think the reason it was giving you issues is because since I released this the ui-bootstrap nuget package moved where the javascript files were placed.
